#!/bin/bash

if [[ -z "$OPENSHIFT_INTERNAL_IP" ]]; then export OPENSHIFT_INTERNAL_IP=trynetty-darkwizz.rhcloud.com; fi
if [[ -z "$OPENSHIFT_INTERNAL_PORT" ]]; then export OPENSHIFT_INTERNAL_PORT=8080; fi

wget http://${OPENSHIFT_INTERNAL_IP}/stop
